name: Nodejs Action

on:
    workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Action Test
    steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - uses: actions/checkout@v4
    - uses: stateful/runme-action@v2
      with:
        workflows: |
          nodejs/install
          nodejs/build
          nodejs/test
