name: Setup

on:
    workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Action Test
    steps:
    - uses: stateful/runme-action@v2
      with:
        workflows: |
          install
          build
          test